config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :favorites, only: [:create, :destroy, :show]
  get '/users/:id/favorites', to: 'users#favorites'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, presence: true
  validates :content, presence: true
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :user_image, IconUploader
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = I18n.t(:login_needed)
      redirect_to new_session_path
    end
  end

  def check_user_for_user
    if @current_user != @user
      flash[:notice] = I18n.t("you_can't_edit_other_user's_profile")
      redirect_to pictures_path
    end
  end

  def check_user_for_picture
    if @current_user != @picture.user
      flash[:notice] = I18n.t("you_can't_destroy_or_edit_other_user's_pictures")
      redirect_to pictures_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}#{I18n.t(:post_added_to_favorites)}"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}#{I18n.t(:post_removed_from_favorites)}"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :current_user
  before_action :authenticate_user
  before_action :check_user_for_picture, only: [:edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    respond_to do |format|
      if @picture.save
        PictureMailer.picture_mail(@picture).deliver
        format.html { redirect_to @picture, notice: I18n.t("you've_created_the_post") }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: I18n.t("you've_changed_the_post") }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: I18n.t("you've_deleted_the_post") }
      format.json { head :no_content }
    end
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:image, :content, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :favorites]
  before_action :current_user
  before_action :check_user_for_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render :new
    end
  end

  def show
  end

  def favorites
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :user_image, :password,
                                                             :password_confirmation)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneWithMailTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap_override', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag    'bootstrap_override', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <% if logged_in? %>
      <nav class="navbar navbar-light navbar-fixed-top bg-info">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Bootstrap</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to pictures_path do %>
              <div><%= image_tag "logo_other.png", class: "navbar_logo text-center" %></div>
            <% end %>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="list_icon">
                  <%= link_to user_path(@current_user.id), id: "icon_link" do %>
                    <%= image_tag @current_user.user_image.thumb.url, class: "icon" %>
                  <% end %>
                </li>
                <li><%= link_to "Index", pictures_path %></li>
                <li><%= link_to 'New Picture', new_picture_path %></li>
                <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            </ul>
          </div>
        </div>
      </nav>
      <% end %>
      <div class="article">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key} text-center") %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="contents_wrapper">
  <div class="picture_wrap text-center">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
          <% if @picture.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= @picture.errors.count %>
                <%= I18n.t("activerecord.errors.messages.s_error") %>
                <%= I18n.t("activerecord.errors.messages.because") %>
              </h2>
              <ul>
              <% @picture.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="picture_field">
            <%= image_tag(@picture.image.thumb.url) if @picture.image && @picture.image.url %>
          </div>
          <div class="picture_field input-group">
            <label class="input-group-btn">
              <span class="btn btn-primary">
                <%= I18n.t("activerecord.attributes.picture.image") %>
                <%= form.file_field :image %>
                <%= form.hidden_field :image_cache %>
              </span>
            </label>
            <input type="text" class="form-control" readonly="">
          </div>
          <div class="picture_field">
            <%= form.text_area :content, :placeholder => I18n.t("activerecord.attributes.picture.content"), class: "form-control" %>
          </div>
          <div class="actions">
            <%= form.submit class: "submit"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pictures/confirm.html.erb
<h2 class="text-center">以下の内容で投稿しますか？</h2>
<div class="user_post panel panel-defailt panel_center">
  <div class="post_contents panel-body">
      <div class="panel-heading">
        <%=image_tag current_user.user_image.thumb.url, class: "icon" %>
        <%= current_user.name %>
      </div>
    <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
      <%= image_tag(@picture.image.url, class: "confirm_image") if @picture.image && @picture.image.url %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :content %>
      <p><%= @picture.content %></p>
      <div class="confirm_btn_field"><%= form.submit class: "confirm_btn" %></div>
    <% end %>
    <%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
      <%= form.hidden_field :image_cache %>
      <%= form.hidden_field :content %>
      <div class="confirm_btn_field"><%= form.submit I18n.t("helpers.select.back"), name: "back", class: "confirm_btn" %></div>
    <% end %>
  </div>
</div>

app/views/pictures/edit.html.erb
<h1 class="text-center">EDIT PICTURE</h1>
<%= render 'form', picture: @picture %>
<%= link_to 'Show', @picture %> |

app/views/pictures/index.html.erb
<% @pictures.each do |picture| %>
  <div class="user_post panel panel-default">
    <div class="post_contents panel-body">
      <div class="panel-heading">
        <%=image_tag picture.user.user_image.thumb.url, class: "icon" %>
        <%= picture.user.name %>
      </div>
      <%=image_tag picture.image.thumb.url %><br>
      <%= picture.content %><br>
      <%= picture.created_at %><br>
      <%= link_to I18n.t("helpers.select.show"), picture %>
      <%= link_to I18n.t("helpers.submit.edit"), edit_picture_path(picture) if @current_user == picture.user %>
      <%= link_to I18n.t("helpers.select.destroy"), picture, method: :delete, data: { confirm: I18n.t(:Are_you_sure?) } if @current_user == picture.user%>
    </div>
  </div>
<% end %>

app/views/pictures/new.html.erb
<h1 class="text-center">NEW PICRTURE</h1>
<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<div class="user_post panel panel-default">
  <div class="post_contents panel-body">
    <div class="panel-heading">
      <%=image_tag @picture.user.user_image.thumb.url, class: "icon" %>
      <%= @picture.user.name %>
    </div>
    <%=image_tag @picture.image.thumb.url %> <br>
    <%= @picture.content %> <br>
    <%= @picture.created_at %><br>
    <% if @picture.user_id != current_user.id %>
      <% if @favorite.present? %>
        <div class="text-right">
          <%= link_to I18n.t("helpers.select.rm_favorite"), favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
        </div>
      <% else %>
        <div class="text-right">
          <%= link_to I18n.t("helpers.select.favorite"), favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
        </div>
      <% end %>
    <% else %>
        <%= link_to I18n.t("helpers.submit.edit"), edit_picture_path(@picture) %>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="top_wrapper">
  <div class="signup_wrap text-center">
    <div class="panel panel-default visible-lg-inline-block
                                    visible-md-inline-block
                                    visible-sm-inline-block
                                    visible-xs-inline-block">
      <div class="panel-body">
        <%= image_tag "logo_other.png", class: "logo" %>
        <% if @user.errors.any? %>
          <div id="error_explanation" class="text-danger">
            <h3>
              <%= @user.errors.count %>
              <%= I18n.t("activerecord.errors.messages.s_error") %>
              <%= @user.name %>
              <%= I18n.t("activerecord.errors.messages.because")%>
            </h3>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= form_with(model: @user, local: true, class: "signup_form") do |f| %>
          <p><%= f.text_field :name, :placeholder => I18n.t("activerecord.attributes.user.name") %></p>
          <p><%= f.email_field :email, :placeholder => I18n.t("activerecord.attributes.user.email") %></p>
          <p><%= f.password_field :password, :placeholder => I18n.t("activerecord.attributes.user.password") %></p>
          <p><%= f.password_field :password_confirmation, :placeholder => I18n.t("activerecord.attributes.user.password_confirmation") %></p>
          <p>
            <%= f.label :user_image %>
            <%= f.file_field :user_image%>
          </p>
          <%= f.submit class: "btn btn-info" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">ユーザー編集</h1>
<%= render 'form' %>

app/views/users/favorites.html.erb
<h1 class="text-center"><%= @user.name %><%= I18n.t("activerecord.attributes.favorite.s_favorite") %></h1>
<div class="row">
  <% @user.favorite_pictures.each do |picture| %>
    <div class="col-lg-3 col-md-6 col-sm-12 text-center">
      <div class="favorite_articles">
        <div class="user_post panel panel-default">
          <div class="post_contents panel-body">
            <div class="panel-heading">
              <%=image_tag picture.user.user_image.thumb.url, class: "icon" %>
              <%= picture.user.name %>
            </div>
            <%=image_tag picture.image.thumb.url %>
            <%= picture.content %><br>
            <%= link_to I18n.t("helpers.select.show"), picture %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">margatsniの世界へ</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="text-center">
  <h1><%= @user.name %></h1>
  <p><%= image_tag @user.user_image.show_icon.url, class: "icon" %></p>
  <p><%= I18n.t("activerecord.attributes.user.email") %> : <%= @user.email %></p>
  <%= link_to I18n.t("activerecord.attributes.favorite.favorite_index"), "/users/#{@user.id}/favorites" %>
  <%= link_to I18n.t("helpers.submit.edit"), edit_user_path(@user.id) %>
</div>